services:
  dev-db:
    image: "postgres:15-alpine"
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: nest_api
    networks:
      - freecodecamp

  test-db:
    image: "postgres:15-alpine"
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: nest_api
    networks:
      - freecodecamp
networks:
  freecodecamp: